# Generated by Django 5.2.5 on 2025-08-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('reader', 'Reader')], default='reader', max_length=10),
        ),
    ]
