# Generated by Django 5.2.5 on 2025-08-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_bio_customuser_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, default='https://facebook.com/', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com/', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, default='https://twitter.com/', null=True),
        ),
    ]
