# Generated by Django 5.2.5 on 2025-08-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_facebook_alter_customuser_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
